### ISSUE TITLE
[FEA] MLOps for Dataset Drift detection

### ISSUE THREAD

**Issue by rnyak** [NVIDIA/NVTabular#533]
When a model is deployed in production, detecting changes and anomalies in new incoming data is critical to make sure that the predictions are valid and can be safely consumed. Therefore, users should be able to analyze drift in their data to understand how it changes over time. Data drift is one of the main reasons for degradation in model accuracy over time. Data drift occurs when statistical properties of input variables (model input data) change (e.g., seasonality, personal preferences, trends change). 
One type of data drift is covariate shift, which refers to the change in the distribution of the input variables present in the training and the new data.

There are existing tools for data and model monitoring.  Examples: Azure ML [datadriftdetector Module](https://docs.microsoft.com/en-us/azure/machine-learning/how-to-monitor-datasets?tabs=python), [ scikit-multiflow](https://scikit-multiflow.github.io/), [Databricks + MLflow ](https://databricks.com/blog/2019/09/18/productionizing-machine-learning-from-deployment-to-drift-detection.html), and [Amazon SageMaker Model Monitor](https://aws.amazon.com/about-aws/whats-new/2019/12/introducing-amazon-sagemaker-model-monitor/).

We'll want to add some of the commonly measured and monitored components to the dataset evaluator and to the dataset generation tool.

**Comment by rnyak** [comment]
@albert17 could you pls review the PR and write down here what stats are already collected? Thanks.

**Comment by albert17** [comment]
These are the stats being collected right now:
```
num_rows:

conts:
  col_name:
      dtype:
      min_val:
      max_val:
      mean:
      std:
      per_nan:
cats:
  col_name:
      dtype:
      cardinality:
      min_entry_size:
      max_entry_size:
      avg_entry_size:
      per_nan:
      multi_min:
      multi_max:
      multi_avg:

labels:
  col_name:
      dtype:
      cardinality:
      per_nan:
```
