### ISSUE TITLE
[BUG] The optimize_criteo.ipynb example fails with 'GPUFileIterator' object has no attribute '_set_dtypes'

### ISSUE THREAD

**Issue by okdimok** [NVIDIA/NVTabular#85]
I have downloaded the latest NVTabular image from NGC.

Then, mapped a folder with the file day_0 from criteo to `/datasets/criteo/crit_orig`

I am getting an error, when I run `optimize_criteo.ipynb`
```python
AttributeErrorTraceback (most recent call last)
<ipython-input-1-84910288ec3f> in <module>
     44         del gdf
     45 path_out = '/raid/criteo/tests/jp_csv_orig/'
---> 46 file_to_pq(train_set, 'csv', output_folder=path_out, cols=cols, dtypes=dtypes)

<ipython-input-1-84910288ec3f> in file_to_pq(target_files, file_type, output_folder, cols, dtypes)
     34     old_file_path = None
     35     writer = None
---> 36     for gdf in tar:
     37 #         gdf.to_parquet(output_folder)
     38         file_path = os.path.join(output_folder, os.path.split(tar.itr.file_path)[1].split('.')[0])

/nvtabular/nvtabular/io.py in __iter__(self)
    329     def __iter__(self):
    330         for path in self.paths:
--> 331             yield from GPUFileIterator(path, **self.kwargs)
    332 
    333 

/nvtabular/nvtabular/io.py in __iter__(self)
    271         for chunk in self.engine:
    272             if self.dtypes:
--> 273                 self._set_dtypes(chunk)
    274             yield chunk
    275             chunk = None

AttributeError: 'GPUFileIterator' object has no attribute '_set_dtypes'
```

I also tried to test the master version of nvtabular by executing inside the container:
```bash
cd /
mv /nvtabular /nvtabular_old
git clone https://github.com/NVIDIA/NVTabular.git nvtabular
```
restarting the kernel and reopenning the file. The error persists.

Additionally, I had minor inconvenience changing the GPUid variable from 4 to 0, which is a more reasonable default. 

**Environment details (please complete the following information):**
 - Environment location: Bare-metal
 - Method of NVTabular install: Docker, nvcr.io/nvidia/nvtabular:0.1
   - Relevant docker-compose parameters
```yaml
stdin_open: true 
    tty: true
    privileged: true 
    ipc: host 
    command: /bin/bash -c "source ~/.bashrc && source activate rapids && CUDA_VISIBLE_DEVICES=1 jupyter lab --ip=0.0.0.0 --allow-root --no-browser --NotebookApp.token='' --NotebookApp.allow_origin='*' --notebook-dir=/"
```
